#!/bin/sh

echo "---SC1000 Update Script v1.3---"

if grep -Fxq -- "---1.3---" /var/osversion; then
	echo "ERROR : This version is already installed"
	umount /tmp/bootpart
	sync
	# just run the local xwax
	/usr/bin/xwax
else
	mkdir /tmp/bootpart

	mount /dev/mmcblk0p1 /tmp/bootpart

	if tar -C /tmp/bootpart/ -xf /media/sda/sc.tar zImage && tar -C /tmp/bootpart/ -xf /media/sda/sc.tar sun5i-a13-olinuxino.dtb && tar -C /usr/bin -xf /media/sda/sc.tar xwax && tar -C /var -xf /media/sda/sc.tar os-version.mp3 && tar -C /var -xf /media/sda/sc.tar scratchsentence.mp3 ; then
		echo "---1.3---" > /var/osversion
		echo "SC1000 software updated!"
		umount /tmp/bootpart
		sync
		tar -C /tmp/ -xf /media/sda/sc.tar successful.mp3
		sync
		mpg123 --loop -1 /tmp/successful.mp3
		
	else
		echo "ERROR : Could not un-tar files"
		umount /tmp/bootpart
		sync
		tar -C /tmp/ -xf /media/sda/sc.tar failed.mp3
		mpg123 --loop -1 /tmp/failed.mp3
	fi
fi


